"""projects table

Revision ID: 26957425227f
Revises: 
Create Date: 2020-02-23 12:32:10.243079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26957425227f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('technologies', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'technologies')
    # ### end Alembic commands ###
