"""users table

Revision ID: 86514c7640d7
Revises: 
Create Date: 2020-02-21 22:01:18.907035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86514c7640d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('about', sa.String(length=50), nullable=True),
    sa.Column('image_file', sa.String(length=120), nullable=True),
    sa.Column('cv_file', sa.String(length=120), nullable=True),
    sa.Column('technical_experience', sa.Text(), nullable=True),
    sa.Column('current_job', sa.Text(), nullable=True),
    sa.Column('educational_background', sa.Text(), nullable=True),
    sa.Column('profession', sa.Text(), nullable=True),
    sa.Column('recent_activities', sa.Text(), nullable=True),
    sa.Column('python', sa.Text(), nullable=True),
    sa.Column('javascript', sa.Text(), nullable=True),
    sa.Column('java', sa.Text(), nullable=True),
    sa.Column('django', sa.Text(), nullable=True),
    sa.Column('flask', sa.Text(), nullable=True),
    sa.Column('nodejs', sa.Text(), nullable=True),
    sa.Column('android', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('github', sa.String(length=200), nullable=False),
    sa.Column('youtube', sa.String(length=200), nullable=False),
    sa.Column('image_file', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project')
    op.drop_table('comment')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('about', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('image_file', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('technical_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_job', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('educational_background', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profession', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('python', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('javascript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('java', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('django', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('flask', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nodejs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('android', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='comment_pkey')
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='project_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_pkey')
    )
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('comments')
    # ### end Alembic commands ###
